markdown: rdiscount
permalink: /:title/
url: http://www.zhangyaowen.com
name: latticet
author: latticet
qq: 1344735273
email: zhangyaowenjy@163.com
duoshuo: yonsm
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 1885061391
github: Yonsm
pygments: true
safe: true
paginate: 20
about: "前端爱好者，长期玩着phpcms，discuz，echsop等的二次开发，熟悉Thinkphp，CI框架的开发。分享工作学习的心得趣事。"
